### ISSUE TITLE
File cannot by found.

### ISSUE THREAD

**Issue by eudennis** [baptistegendron/gulp-svg-inject#1]
I can't use it because the plugin won't file the svg file. 

`Error: Could not find/read SVG file (img/menu.svg): Error: ENOENT: no such file or directory, open './img/menu.svg'`

In my HTML I'm using:

`<img src="img/menu.svg" alt="">`

I'm I missing something?

**Comment by bateast2** [comment]
Hi,

I could not reproduce your issue.
If you use relative path, make sure to make them relative to the folder where you execute gulp.
Alternatively you can use absolute path.

**Comment by eudennis** [comment]
Ok, thanks :) I will try!
